name: ostra
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.0
  hooks_riverpod: ^2.5.1
  phosphor_flutter: ^2.0.1
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  flutter_gen_runner: ^5.4.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.2
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  go_router_builder: ^2.4.1

flutter_gen:
  output: lib/utils/assets/
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
