name: Analayze PR

on:
  pull_request:
    branches: [main, test]

jobs:
  analyze_build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.5"
          channel: "stable"
          cache: true
      - name: Check flutter version
        run: flutter --version
      - name: Run dart analyzer
        run: flutter analyze
      - name: Run the tests
        run: flutter test
      - name: Build the app
        run: flutter build web
      - name: Cleanup
        run: rm -rf ${HOME}/.git-credentials
